### ISSUE TITLE
Create shiny version of qq.gam then enables zooming

### ISSUE THREAD

**Issue by mfasiolo** [mfasiolo/mgcViz#13]
It would be quite easy to create an app where by drawing a rectangle on the plot (basic shiny feature) we get the corresponding xlim and ylim, which then get passed to zoo.qqGam(), which does the binning and the plotting.

**Comment by ghost** [comment]
See commit 428d334fb555e0db9cb728b8f3dea90e6d8bf3a9 for a first version of a shiny gadget. With rstudio it returns the call which would render the plot obtained just before the app is closed.

**Comment by mfasiolo** [comment]
Well done, I'll consider this closed!
