### ISSUE TITLE
plot.mgcv.smooth1D dTrans argument for conditional density of residuals

### ISSUE THREAD

**Issue by ghost** [mfasiolo/mgcViz#18]
I removed the `dTrans` argument as it was not called. 

Do we want to reintroduce it as an argument for plot.mgcv.smooth1D or should we keep only the default (cubic root) ?

**Comment by mfasiolo** [comment]
Now `dTrans` is corrected implemented, see 6f5c5bd676b9e800ce3045ce9d3df254a3bcead9
