### ISSUE TITLE
Add level numbering in contour plots

### ISSUE THREAD

**Issue by mfasiolo** [mfasiolo/mgcViz#4]
Needed in plot.mgcv.smooth.2D, plot.sos.smooth, check.mgcv.smooth.2D and maybe others.

**Comment by ghost** [comment]
I am investigating the `directlabels` library. Maybe we can find a simple solution inside this library. It seems to work on some examples (https://i.stack.imgur.com/0OVOr.png) even if it is not exactly what we want probably.

**Comment by mfasiolo** [comment]
I've seen it too, I was surprised that there seems to be no simple solution to this!

**Comment by mfasiolo** [comment]
Ok so, as of this 292222367444ef9de74edc9a6dc827663c13294b commit, the ugly way of doing this should be:

```
library(mgcViz)
set.seed(2) ## simulate some data...
dat <- gamSim(1, n = 700, dist = "normal", scale = 2)
b <- gam(y ~ s(x0) + s(x1, x2) + s(x3), data = dat, method = "REML")
b <- getViz(b)

# Plot 2D effect with noised-up raster, contour and rug for design points 
# Opacity is proportional to the significance of the effect
pl <- plot(sm(b, 2)) + l_fitRaster() + l_fitContour(mapping = aes(z = tz, colour = ..level..), colour = "black") 

library(directlabels)
direct.label(pl$ggObj, list("bottom.pieces", colour='black'))
```

Maybe this belongs to an mgcViz FAQ document!

**Comment by DrongosMind** [comment]
`metR::geom_label_contour()` and `metR::geom_text_contour()` might be what you need? https://eliocamp.github.io/metR/reference/geom_text_contour.html

**Comment by mfasiolo** [comment]
Thanks for pointer! I am a bit reluctant to add an extra dependency just to get the contour labels, but it's nice to see that there is a way to add them

**Comment by DrongosMind** [comment]
I notice that the following works exactly as expected:
```
plot.mgcv.smooth.2D(x) + 
    l_fitRaster() + 
    l_fitContour() + 
    geom_label_contour()
```
So, no changes to the library are needed to support contour labels (except perhaps a mention in the documentation).

**Comment by mfasiolo** [comment]
Thanks, great to see that this works out of the box!
