### ISSUE TITLE
Wrong definition of default distance in l_densCheck doc

### ISSUE THREAD

**Issue by fabian-s** [mfasiolo/mgcViz#42]
Says "abs(sqrt(em)-sqrt(th))^(1/3)", should be "(sqrt(em)-sqrt(th))^(1/3)".

**Comment by mfasiolo** [comment]
Corrected here fbb8d0d9515c2086c094353beb8a544a729d4e1c, thanks!

**Comment by fabian-s** [comment]
hotdamn, you're quick! :open_mouth:
