### ISSUE TITLE
Allow bare variable names in l_XXX calls

### ISSUE THREAD

**Issue by fabian-s** [mfasiolo/mgcViz#43]
Thx for this great package!  

I think it would be even more awesome if I didn't have to "quote" all my "variables".  
`check1D(v, x = x3)` :+1:  , `check1D(v, x = "x3")` :-1:

**Comment by mfasiolo** [comment]
Thanks, I'm glad someone is using it!

I was thinking about it, but it is a bit difficult to cover all the cases:

- `check1D(v, x = "x3")` with x3 in `fit$model`;

- `check1D(v, x = 1:10)` ;

-  `check1D(v, x = x4)`  with global variable `x4 <- 1:10`; 

- `check1D(v, x = xv[1])` with global `xv <- c("x1", "x2")` and `x1`, `x2` in `fit$model`;

By using "quotes" to distinguish variables in `fit$model` from the global ones it is easy to cover the 4 cases, but maybe something better can be done using `substitute`, `parse` etc.

**Comment by fabian-s** [comment]
I see, yeah, that's (too) tough to solve....
