### ISSUE TITLE
l_densCheck should use scale_fill_gradient2 

### ISSUE THREAD

**Issue by fabian-s** [mfasiolo/mgcViz#44]
Arguably, dFun is on a divergent scale with a natural midpoint at 0, so it should use a divergent color scale with fixed `midpoint = 0` so that a divergence of 0 is visually identical across models, the border beween under- and over-represented residual values is more vivid and the colors corresponding to "no relevant divergence between observed and expected density" cannot change depending on the extremes of the observed distances. 

Thx for the great package. Just playing around with settings and options and adding my impressions :)

**Comment by mfasiolo** [comment]
Thanks, this is addressed in 8f329e1a3707fc8997f31c4d1826f728e7c2ac9c. This scale is much better, so maybe I'll finally be able to explain people what this function actually does! :)
