### ISSUE TITLE
Passing ... to ggplot functions

### ISSUE THREAD

**Issue by mfasiolo** [mfasiolo/mgcViz#5]
We need to work out how to do this without generating too many warnings.

**Comment by ghost** [comment]
I think this could be the way to go for `aes`. We need to take into account the default which works with NSE. `aes_q`, `aes_` or `aes_string`work differently. See here: (http://ggplot2.tidyverse.org/reference/aes_.html).

```r
library(ggplot2)
f <- function(..., data) {
  g <- ggplot(data = data, aes_q(...)) + geom_point()
  return(g)
}
f(x = ~Sepal.Length, y = ~Sepal.Width, data = iris)
```

This seems to work for me. Not sure about passing other arguments than aes... - dunno if it is relevant.

**Comment by mfasiolo** [comment]
It seems to me that the real difficulty is when we want to pass ... to several ggplot function, eg:

```
fn <- function(...){
ggplot(faithfuld, aes(waiting, eruptions), ...) +
  geom_raster(aes(fill = density), ...) + 
  geom_contour(aes(z = density), ...)
}
fn(linetype = 2)
#Warning: Ignoring unknown parameters: linetype
```

here we want to pass "linetype" to geom_contour via (...), but geom_raster issues a warning, because it does not take linetype as an argument. Only reasonable solutions I can think of is:

```
fn <- function(...){
  .pl <- ggplot(faithfuld, aes(waiting, eruptions), ...)
  
  .tmpF <- function(o, linetype=1, ...)
  {
    o <- o + geom_raster(aes(fill = density), ...) + geom_contour(aes(z = density), linetype=linetype, ...)
  }
  .pl <- .tmpF(.pl, ...)
  .pl
}
fn(linetype = 2)
```

But this can be quite time consuming.

**Comment by ghost** [comment]
Ok I see. In anycase we can have the same problem with anykind of function; e.g where

```r
f <- function(...) {
    g(...)
    h(...)
}
```
Where args from g & h would differ (sometimes it would throw a warning, sometimes an error I guess)
A interesting link : https://rpubs.com/hadley/ggplot2-layers. I take a look at it and try to come with a solution

**Comment by ghost** [comment]
What about something like this ?

```r
library(ggplot2)

f <- function(..., layer_1 = list(), layer_2 = list()) {
  extraArgs <- list(...)
  g <- ggplot(faithfuld, aes(waiting, eruptions)) +
    do.call("geom_raster", c(list(mapping = aes(fill = density)), layer_1)) + 
    do.call("geom_contour", c(list(mapping = aes(z = density)), layer_2))
  # ...
  g
}

f(layer_1 = list(), layer_2 = list(linetype = 2, colour = "red"))
```
With this approach I think we can easily split extra params for each layer and control that they are valid. In anycase the `...` are problematic if say `g()` and `h()` share the some parameters (e.g `x`) but we want to set them differently. I think we could also have an easier documentation: we can explain what are the parameters available layer by layer.

What do you think about this ?

**Comment by mfasiolo** [comment]
This seems a good solution to me. Maybe I would call the lists argRast and argCon rather than layer_1 and layers_2, so an user would have an intuition about where those arguments will go. Using this approach we might also reduce the number of arguments that the plotting functions take (by including some arguments in the lists).

**Comment by ghost** [comment]
Yes I agree explicit names for layers should be better - we just need to keep them consistant from one plot to another - argRast for all raster layer, etc. I am ok with this!

**Comment by ghost** [comment]
Closing for now.
