### ISSUE TITLE
Possible to plot combined effect of smooth and standard terms?

### ISSUE THREAD

**Issue by philippberens** [mfasiolo/mgcViz#63]
Great package.

I have a gam with one smooth and an intercept and for a paper, would like to plot the combined effect of both. Is there a way to do this @mfasiolo?

**Comment by mfasiolo** [comment]
Dear Philipp,

 sorry for the late reply, maybe you could use the seWithMean argument in
plot.mgcv.smooth.1D ?

Best,

Matteo
