### ISSUE TITLE
change colour scheme and color scale of 2D contour plot

### ISSUE THREAD

**Issue by gravems** [mfasiolo/mgcViz#67]
Hi, I run a 2-way GAM using the mgcv package testing the interactive effects of water velocity and temperature on mussel cover. I used mgcViz package and getViz() to visualize the model, and would like to override some of the defaults of the figure. I want to change the colour palette from viridis to Spectral (or at least a scale from blue to red) and force the scale for the color palette to a fixed value (between -2.2 and 1.5) so I can compare figures from different models. I have tried the following, but the scale_fill_gradient() and scale_color_gradient() commands aren't changing the figure. The scale_fill_gradient() command gives a "scale for 'fill' is already present" warning, but adding another scale doesn't actually change the figure, it is still on the default from ~-1 to 0.8.

Mytilus_P<-Biotic_AllQuads_PisasterPres_2019_10_30$Mytilus
PredVeloc_P<-Biotic_AllQuads_PisasterPres_2019_10_30$PredVeloc
PredRoboma_P<-Biotic_AllQuads_PisasterPres_2019_10_30$PredRobomax

GAM_P<-gam(Mytilus_P ~  s(PredRoboma_P, bs = "tp", k = 11) + 
  +  s(PredVeloc_P, bs = "tp", k = 11) + s(PredVeloc_P, PredRoboma_P, bs = "tp", k = 100), family = binomial())

GAM_PViz<-getViz(GAM_P)

plot(sm(GAM_PViz,3))+ labs(title = "Pisaster present") + xlab("Avg water velocity (cm/s)")+ ylab("Avg max daily mussel temperature (c)") + scale_fill_gradient(limits = c(-2.2,1.5))
#warning
Scale for 'fill' is already present. Adding another scale for 'fill', which will replace the existing scale.

![PisasterPres_Temp-Wave](https://user-images.githubusercontent.com/46694098/68887867-9e794a00-06ce-11ea-8231-d9f38b7ca07f.png)

**Comment by mfasiolo** [comment]
Hi, 

 Consider the following example:

```
library(mgcv)
set.seed(2) ## simulate some data... 
dat <- gamSim(1,n=400,dist="normal",scale=2)
b <- gamV(y~s(x0,x1),data=dat)

plot(sm(b,1)) + scale_fill_gradient(limits = c(-2.2,1.5)) 
```

Here `scale_fill_gradient` does not have any effect, as in your example. The reason is that we are not adding any layer (e.g. `l_fitRaster`) to the plot. Given that the plot is empty, the layers are added automatically by `plot.plotSmooth`. That is, the code above is equivalent to:
```
plot(sm(b,1)) + scale_fill_gradient(limits = c(-2.2,1.5)) + l_fitRaster() + l_fitContour()
```
Where `l_fitContour` internally calls `scale_fill_gradient`, thus overwriting our explicit call.
The solution is doing:
```
plot(sm(b,1)) + l_fitRaster() + l_fitContour() + scale_fill_gradient(limits = c(-2.2,1.5))
```
Do this help? By the way, I apologise for the fact that the behaviour of `print.plotSmooth` is somewhat undocumented at the moment.

**Comment by gravems** [comment]
Oh my gosh I just saw this post! Thanks so so much, it works! No wonder it wasn't working before. Thanks for the detailed explanation

**Comment by mfasiolo** [comment]
No worries!
