### ISSUE TITLE
simulate swaps rows / columns

### ISSUE THREAD

**Issue by florianhartig** [mfasiolo/mgcViz#70]
Hi Matteo, see https://github.com/florianhartig/DHARMa/issues/144

**Comment by mfasiolo** [comment]
Hi Florian, this should be solved by this commit https://github.com/mfasiolo/mgcViz/commit/7794c9ebea97726b686c99cac9c42fc97b9272fe .

Thanks,

Matteo

**Comment by florianhartig** [comment]
OK, thanks. Do you know when this will be rolled out on CRAN?

**Comment by mfasiolo** [comment]
I was not planning to upload a new version of CRAN in the next month or so (it's supposed to be a quick thing, but there is always some problem and I end up losing a whole day). But hopefully this should not slow you down, given that DHARMa does not depend on mgcViz.

**Comment by florianhartig** [comment]
OK, no problem, just to know.
