### ISSUE TITLE
Tip for sending mgcViz object to cowplot

### ISSUE THREAD

**Issue by tmeeha** [mfasiolo/mgcViz#72]
Seems like the cowplot library has a hard time converting an mgcViz plot object to a grob for plotting because the object contains multiple classes, with a ggplot part and a data part. Therefore, when assigning an mgcViz object for plotting with other packages, it is worth subsetting it first, as in: ggplot_object_for_cowplot <- name_of_mgcviz_object$ggObj.

**Comment by mfasiolo** [comment]
Yes, indeed the cowplot library does not know anything about objects of class "gamViz" and you need to extract the object the ggObj slot manually. The same applies to ggplot, gridExtra etc. I am closing this issue because I don't see what could be done about this.
