### ISSUE TITLE
Add argument to exclude terms in simulate.gam

### ISSUE THREAD

**Issue by gimickwu** [mfasiolo/mgcViz#73]
Thanks for making this package! 

Would it be possible to allow extra arguments to exclude model terms in simulate.gam()? For example, I would like to exclude the random effects of my model in simulations. I guess something like passing the 'exclude' argument to predict.gam() might do it, but I haven't figured out how to do it.

Cheers,
Mick

**Comment by mfasiolo** [comment]
Hi Mick, 

 Are you currently able to exclude terms when using `predict.gam()` via the `exclude` argument (I haven't tried)? If so, I could simply add an `exclude` argument to `simulate.gam` and pass it to `predict.gam` internally.

Best,

Matteo

**Comment by gimickwu** [comment]
Hi Matteo,

Yes, it’s relatively new:
https://www.rdocumentation.org/packages/mgcv/versions/1.8-33/topics/predict.gam

Best,
Mick

**Comment by mfasiolo** [comment]
Ok, then 55e1c245fc444ffd59169cf7fc94d300a979b04e should sort it? Please try to install the latest github version of mgcViz to see whether this works for you.

Best,

Matteo

**Comment by gimickwu** [comment]
I've installed the latest  version and it's working! Thank you for looking into this so quickly.

Best,
Mick

**Comment by mfasiolo** [comment]
No worries, thank you for opening this issue!

Matteo
