### ISSUE TITLE
Could rgl be moved to imports?

### ISSUE THREAD

**Issue by florianhartig** [mfasiolo/mgcViz#75]
While testing code related to https://github.com/florianhartig/DHARMa/issues/309, I have the following problem on Mac: 

- library(mgcViz) fails on loading because it imports rgl, and rgl will fail to load if Quartz (x11 system) is not installed on the Mac, and this is not installed automatically via CRAN. 
- Also, even when not attaching mgcViz, calling mgcViz:::simulate.gam in DHARMa is attaching rgl and opening a Quartz window on Mac, which is a bit annoying. 

I believe both is caused by having rgl in import instead of depends, which means that rgl will always be attached once mgcViz is attached or used, instead of only attaching the dll if rgl is actually used.

I am not very happy to introduce these unnecessary hard dependencies in DHARMa. May I ask if there is a particular reason to have rgl in imports instead of depends? Same could actually be asked for qgam and ggplot2, seems not strictly necessary to me to have them in depends?

**Comment by mfasiolo** [comment]
I am looking into this, switching to an import should not be a problem but I need to run some tests. Overall, the dependency on rgl has been a pain throughout!

**Comment by florianhartig** [comment]
That would be great. I have a DHARMa branch with the mgcViz dependency ready, but I would not like to merge it into my main branch before this is on CRAN, because the rgl dependency is very persistent / annoying. 

I think once this is away from import, rgl should only be loaded once it is actually used, which helps a lot I would think.

**Comment by florianhartig** [comment]
Hi Matteo, any news on this? I would be ready to switch DHARMa to mgcViz once this is resolved ...

**Comment by mfasiolo** [comment]
HI Florian, sorry for being so slow! I am trying a more radical solution, that is to make rgl a Suggest so that you will not have to install it at all.

**Comment by florianhartig** [comment]
Hi Matteo, I think this was solved wit the last CRAN update, right? All my DHARMa checks work fine, so I'm in the process of including the mgcViz dependency with the next DHARMa update on CRAN. 

Thanks for your help!

**Comment by mfasiolo** [comment]
Hi Florian, yes this should be solved now. Fingers crossed that I've not overlooked anything!
