### ISSUE TITLE
effect plots for binomial gam?

### ISSUE THREAD

**Issue by wcornwell** [mfasiolo/mgcViz#77]
Apologies if I over-looked this, but do you have any recommendations for making effect plots for a binomial gam?

**Comment by mfasiolo** [comment]
Hi Will, maybe I am missing something, but I think you could use the standard effect plots provided by mgViz.

**Comment by wcornwell** [comment]
Hi @mfasiolo, sorry for the short and cryptic issue.  This is basically about handling the link functions elegantly to improve the interpretability of the y-axis of the final plot.  Here is more explanation:

```{r}
##### gam example
# Simulate data
library(mgcViz)
set.seed(2) ## simulate some data...
dat <- gamSim(eg=1,n=1000,dist="binary",scale=2)

# Fit GAM and get gamViz object
b <- gam(y~s(x0), data=dat, family=binomial(link = "logit"),method="REML", scale = 2)
b1 <- getViz(b, nsim = 20)

print(plot(b1))
```
gives me:
![image](https://user-images.githubusercontent.com/5534161/141705084-45ac22c3-61a7-42c4-ba6c-c39d2f48f9c1.png)

which is great except that the y-axis is logit transformed. i was hoping for something more like:

```{r}
plot(inv.logit(b1$fitted.values)~dat$x0)
```
so that the y-axis would be interpretable.  Any thoughts?

**Comment by mfasiolo** [comment]
Ok, to get a plot on the probability scale you should do:
```
plot(b1, select = 1, trans = function(x) b$family$linkinv(b$coef[1]+x))
```
Note that we are adding in the intercept manually for this kind of plot to make sense.
